check
qwerty-yhn/java-explore-with-me1 pull request #1
Opened 2023-07-09 16:34 UTC by qwerty-yhn

2023-07-10 18:01 UTC, qwerty-yhn commented
Серега Привет!)))) Это случилось) проект не стабильно работает, хз почему. База на гите не отрабатывает чтоли, короче хз

2023-07-11 14:38 UTC, krylov-sergey-sergeevich requested changes
Привет, в целом неплохо, давай по мелочам пройдемся

- Давай избавимся от конструкторов при помощи аннотаций
- Обсудим заметки

2023-07-11 14:38 UTC, krylov-sergey-sergeevich commented on ewm-main-service/src/main/java/ru/practicum/category/controller/CategoryControllerAdmin.java
> +    @Autowired
лучше request arg contrustor воспользоваться

2023-07-11 14:38 UTC, krylov-sergey-sergeevich commented on ewm-main-service/src/main/java/ru/practicum/events/event/controller/EventControllerAdmin.java
> +    List<EventFullDto> getAllEventsForAdmin(@RequestParam(required = false) List<Long> users,
public

2023-07-11 14:38 UTC, krylov-sergey-sergeevich commented on ewm-main-service/src/main/java/ru/practicum/events/event/controller/EventControllerAdmin.java
> +    EventFullDto updateEventById(@PathVariable Long eventId,
public

2023-07-11 14:38 UTC, krylov-sergey-sergeevich commented on ewm-main-service/src/main/java/ru/practicum/events/event/service/impl/EventServiceAdminImpl.java
> +    public static final String DATE_TIME_FORMAT = "yyyy-MM-dd HH:mm:ss";
Я бы вынес в DateUtils или Constants

2023-07-11 14:38 UTC, krylov-sergey-sergeevich commented on ewm-main-service/src/main/java/ru/practicum/events/event/service/impl/EventServicePrivateImpl.java
> +    public static final String DATE_TIME_FORMAT = "yyyy-MM-dd HH:mm:ss";
дубль

2023-07-11 14:38 UTC, krylov-sergey-sergeevich commented on ewm-main-service/src/main/java/ru/practicum/events/event/service/impl/EventServicePrivateImpl.java
> +                throw new BadRequestException("");
Улучшить

2023-07-11 14:38 UTC, krylov-sergey-sergeevich commented on ewm-main-service/src/main/java/ru/practicum/events/event/service/impl/EventServicePrivateImpl.java
> +                throw new BadRequestException("");
Улучшить

2023-07-11 14:38 UTC, krylov-sergey-sergeevich commented on ewm-main-service/src/main/java/ru/practicum/events/event/service/impl/EventServicePublicImpl.java
> +    public static final String DATE_TIME_FORMAT = "yyyy-MM-dd HH:mm:ss";
повтор

2023-07-11 14:38 UTC, krylov-sergey-sergeevich commented on ewm-main-service/src/main/resources/schema.sql
> +                                name VARCHAR(255) NOT NULL,
Лучше вот так делать:
CONSTRAINT pk_user PRIMARY KEY (id),

2023-07-11 14:38 UTC, krylov-sergey-sergeevich commented on ewm-main-service/src/test/java/ru/practicum/MainServiceApplicationTest.java
> +    void main() {
Лучше название тестов делать mainTest вот так

2023-07-11 14:38 UTC, krylov-sergey-sergeevich commented on ewm-stat-service/stats-dto/pom.xml
> +            <version>4.13.2</version>
Почему 4 выбран?

2023-07-11 14:38 UTC, krylov-sergey-sergeevich commented on ewm-stat-service/stats-dto/pom.xml
> +            <version>2.14.2</version>
версии лучше в проперти блок выносить

2023-07-11 14:38 UTC, krylov-sergey-sergeevich commented on ewm-stat-service/stats-server/pom.xml
> +            <version>2.7.2</version>
зачем тут версия?

2023-07-11 14:38 UTC, krylov-sergey-sergeevich commented on ewm-stat-service/stats-server/pom.xml
> +            <artifactId>assertj-core</artifactId>
Для чего?

2023-07-11 14:38 UTC, krylov-sergey-sergeevich commented on ewm-stat-service/stats-dto/src/main/java/ru/practicum/explorewithme/stats/dto/HitDto.java
> +    @Pattern(regexp = "\\d{4}-\\d{2}-\\d{2} \\d{2}:\\d{2}:\\d{2}")
@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss") - так нельзя?

2023-07-11 14:38 UTC, krylov-sergey-sergeevich commented on ewm-stat-service/stats-server/src/main/resources/schema.sql
> +CREATE INDEX hits_app_field ON hits (app);
Не перебор с индексами?)

2023-07-12 16:05 UTC, qwerty-yhn commented on ewm-main-service/src/main/java/ru/practicum/category/controller/CategoryControllerAdmin.java
> +    @Autowired
Поправил!)

2023-07-12 16:28 UTC, qwerty-yhn commented on ewm-main-service/src/main/java/ru/practicum/events/event/controller/EventControllerAdmin.java
> +    List<EventFullDto> getAllEventsForAdmin(@RequestParam(required = false) List<Long> users,
Поправил)

2023-07-12 16:28 UTC, qwerty-yhn commented on ewm-main-service/src/main/java/ru/practicum/events/event/controller/EventControllerAdmin.java
> +    EventFullDto updateEventById(@PathVariable Long eventId,
поправил

2023-07-12 16:34 UTC, qwerty-yhn commented on ewm-main-service/src/main/java/ru/practicum/events/event/service/impl/EventServiceAdminImpl.java
> +    public static final String DATE_TIME_FORMAT = "yyyy-MM-dd HH:mm:ss";
сделал

2023-07-12 16:35 UTC, qwerty-yhn commented on ewm-main-service/src/main/java/ru/practicum/events/event/service/impl/EventServicePrivateImpl.java
> +    public static final String DATE_TIME_FORMAT = "yyyy-MM-dd HH:mm:ss";
поправил

2023-07-12 16:39 UTC, qwerty-yhn commented on ewm-main-service/src/main/java/ru/practicum/events/event/service/impl/EventServicePrivateImpl.java
> +                throw new BadRequestException("");
ага

2023-07-12 16:40 UTC, qwerty-yhn commented on ewm-main-service/src/main/java/ru/practicum/events/event/service/impl/EventServicePrivateImpl.java
> +                throw new BadRequestException("");
ага

2023-07-12 16:42 UTC, qwerty-yhn commented on ewm-main-service/src/main/java/ru/practicum/events/event/service/impl/EventServicePublicImpl.java
> +    public static final String DATE_TIME_FORMAT = "yyyy-MM-dd HH:mm:ss";
ага

2023-07-12 18:04 UTC, qwerty-yhn commented on ewm-main-service/src/main/resources/schema.sql
> +                                name VARCHAR(255) NOT NULL,
Поправил, а подскажи это лучше с точки зрения читабельности? хотя вроде делают то одно и тоже. Расскажи почему лучше так?

2023-07-12 18:06 UTC, qwerty-yhn commented on ewm-main-service/src/test/java/ru/practicum/MainServiceApplicationTest.java
> +    void main() {
Ну да так логичнее

2023-07-12 18:32 UTC, qwerty-yhn commented on ewm-stat-service/stats-dto/pom.xml
> +            <version>4.13.2</version>
Как таковой причины нет) Использовал 4 потому-что для 5 надо по другому записать artifactId и groupId. Можно и с 5 я вот обновил)

2023-07-12 18:37 UTC, qwerty-yhn commented on ewm-stat-service/stats-dto/pom.xml
> +            <version>2.14.2</version>
Сделал, так удобнее

2023-07-12 19:07 UTC, qwerty-yhn commented on ewm-stat-service/stats-server/src/main/resources/schema.sql
> +CREATE INDEX hits_app_field ON hits (app);
Чет перебор да)))

2023-07-13 04:50 UTC, krylov-sergey-sergeevich commented on ewm-main-service/src/main/resources/schema.sql
> +                                name VARCHAR(255) NOT NULL,
в случае если тебе придется удалить констрейнт и у тебя не будет доступа в бд или бд будет на разных стендах чутка разная то точное имя дает возможность производить операции с объектом не боясь что может быть рассинхрон

2023-07-13 04:50 UTC, krylov-sergey-sergeevich commented on ewm-main-service/src/main/resources/schema.sql
> +                                name VARCHAR(255) NOT NULL,
это скорее важно для больших уже продакшен систем с множеством стендов на которых работает софт и долгим жизненным циклом

2023-07-13 04:51 UTC, krylov-sergey-sergeevich commented on ewm-stat-service/stats-dto/pom.xml
> +            <version>4.13.2</version>
вроде в спринг буде 5 по умолчанию они стремятся поддерживать я бы в его сторону всегда смотрел

2023-07-13 19:16 UTC, krylov-sergey-sergeevich approved these changes
Привет, зачет!

2023-07-13 19:16 UTC, krylov-sergey-sergeevich commented on ewm-main-service/src/main/resources/schema.sql
> +                                    CONSTRAINT pk_user PRIMARY KEY (id)
p.s как мы понимаем такой подход рекомендуется во всех таблицах использоваться, а не одной, но это по желанию =)

2023-07-13 19:16 UTC, krylov-sergey-sergeevich commented on ewm-stat-service/stats-dto/pom.xml
> +            <version>5.7.2</version>
вот так и версию вынести в проперти блок

2023-07-17 17:48 UTC, merged